### PR TITLE
Prevented draw() from overwriting previous selection

### PR DESCRIPTION
**Pull request by jasonn85**
I know this PR into YSSegmentedControl is a bit stale, but I liked the change and made this one more tweak to avoid an issue when changing titles.

### CODE REVIEW

**Comment by jeffaburt** [comment]
This is great! Did you also make the change on https://github.com/yemeksepeti/YSSegmentedControl for everyone targeting the main fork?

**Comment by jasonn85** [comment]
This PR would, if merged, affect stockx's PR into the main fork at https://github.com/yemeksepeti/YSSegmentedControl/pull/15

**Comment by jeffaburt** [comment]
Ahh I see what's going on. This PR was originally opened against `stockx:master`. The PR you linked is using `stockx:update-selector-in-layout-subviews` and not `stockx:master`. I went ahead and changed this PR to target `stockx:update-selector-in-layout-subviews` instead. Thanks for the contribution! I'll get this merged in right away.

**Comment by jasonn85** [comment]
Oh, my mistake.  I had set it to go toward that branch but must have accidentally switched it back.

**Pull request merged**
